--[[
    init.lua
    Created: 07/14/2024 15:22:33
    Description: Autogenerated script file for the map pmdras_overworld.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local pmdras_overworld = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---pmdras_overworld.Init(zone)
--Engine callback function
function pmdras_overworld.Init(zone)


end

---pmdras_overworld.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function pmdras_overworld.EnterSegment(zone, rescuing, segmentID, mapID)


end

---pmdras_overworld.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function pmdras_overworld.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---pmdras_overworld.Rescued(zone, name, mail)
--Engine callback function
function pmdras_overworld.Rescued(zone, name, mail)


end

return pmdras_overworld

