--[[
    init.lua
    Created: 07/19/2024 11:16:49
    Description: Autogenerated script file for the map poison_bar.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local poison_bar = {}

-------------------------------
-- Map Callbacks
-------------------------------
---poison_bar.Init(map)
--Engine callback function
function poison_bar.Init(map)


end

---poison_bar.Enter(map)
--Engine callback function
function poison_bar.Enter(map)

  GAME:FadeIn(20)

end

---poison_bar.Exit(map)
--Engine callback function
function poison_bar.Exit(map)


end

---poison_bar.Update(map)
--Engine callback function
function poison_bar.Update(map)


end

---poison_bar.GameSave(map)
--Engine callback function
function poison_bar.GameSave(map)


end

---poison_bar.GameLoad(map)
--Engine callback function
function poison_bar.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return poison_bar

