--[[
    init.lua
    Created: 07/12/2024 12:13:07
    Description: Autogenerated script file for the map sandy_tombs.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local sandy_tombs = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---sandy_tombs.Init(zone)
--Engine callback function
function sandy_tombs.Init(zone)


end

---sandy_tombs.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function sandy_tombs.EnterSegment(zone, rescuing, segmentID, mapID)


end

---sandy_tombs.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function sandy_tombs.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---sandy_tombs.Rescued(zone, name, mail)
--Engine callback function
function sandy_tombs.Rescued(zone, name, mail)


end

return sandy_tombs

