--[[
    init.lua
    Created: 08/13/2024 08:38:30
    Description: Autogenerated script file for the map lost_city.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local lost_city = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---lost_city.Init(zone)
--Engine callback function
function lost_city.Init(zone)


end

---lost_city.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function lost_city.EnterSegment(zone, rescuing, segmentID, mapID)


end

---lost_city.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function lost_city.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---lost_city.Rescued(zone, name, mail)
--Engine callback function
function lost_city.Rescued(zone, name, mail)


end

return lost_city

