--[[
    init.lua
    Created: 07/16/2024 18:09:47
    Description: Autogenerated script file for the map malevolent_river_basin.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local malevolent_river_basin = {}

-------------------------------
-- Map Callbacks
-------------------------------
---malevolent_river_basin.Init(map)
--Engine callback function
function malevolent_river_basin.Init(map)


end

---malevolent_river_basin.Enter(map)
--Engine callback function
function malevolent_river_basin.Enter(map)

  GAME:FadeIn(20)

end

---malevolent_river_basin.Exit(map)
--Engine callback function
function malevolent_river_basin.Exit(map)


end

---malevolent_river_basin.Update(map)
--Engine callback function
function malevolent_river_basin.Update(map)


end

---malevolent_river_basin.GameSave(map)
--Engine callback function
function malevolent_river_basin.GameSave(map)


end

---malevolent_river_basin.GameLoad(map)
--Engine callback function
function malevolent_river_basin.GameLoad(map)

  GAME:FadeIn(20)

end

function malevolent_river_basin.Pecharunt_Statue_Action(chara, activator)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Statue_Talk']))
end

function malevolent_river_basin.Map_Exit_Touch(chara, activator)
    -- There should ideally be a confirmation box here
    UI:ChoiceMenuYesNo("Leave the area?", true)
    UI:WaitForChoice()
    ch = UI:ChoiceResult()
    if ch then
        GAME:EnterZone('pmdras_overworld', -1, 1, 0)
    end
end

-------------------------------
-- Entities Callbacks
-------------------------------


return malevolent_river_basin

