--[[
    init.lua
    Created: 07/14/2024 23:10:04
    Description: Autogenerated script file for the map godhome.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local godhome = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---godhome.Init(map)
--Engine callback function
function godhome.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---godhome.Enter(map)
--Engine callback function
function godhome.Enter(map)

  GAME:FadeIn(20)

end

---godhome.Exit(map)
--Engine callback function
function godhome.Exit(map)


end

---godhome.Update(map)
--Engine callback function
function godhome.Update(map)


end

---godhome.GameSave(map)
--Engine callback function
function godhome.GameSave(map)


end

---godhome.GameLoad(map)
--Engine callback function
function godhome.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return godhome

