--[[
    init.lua
    Created: 07/14/2024 11:43:16
    Description: Autogenerated script file for the map base_camp_2_pmdras.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local base_camp_2_pmdras = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---base_camp_2_pmdras.Init(map)
--Engine callback function
function base_camp_2_pmdras.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---base_camp_2_pmdras.Enter(map)
--Engine callback function
function base_camp_2_pmdras.Enter(map)

  GAME:FadeIn(20)

end

---base_camp_2_pmdras.Exit(map)
--Engine callback function
function base_camp_2_pmdras.Exit(map)


end

---base_camp_2_pmdras.Update(map)
--Engine callback function
function base_camp_2_pmdras.Update(map)


end

---base_camp_2_pmdras.GameSave(map)
--Engine callback function
function base_camp_2_pmdras.GameSave(map)


end

---base_camp_2_pmdras.GameLoad(map)
--Engine callback function
function base_camp_2_pmdras.GameLoad(map)

  GAME:FadeIn(20)

end

function base_camp_2_pmdras.Talking_Gabite_Action(chara, activator)
    GROUND:CharTurnToChar(chara,CH('PLAYER'))
    UI:SetSpeaker(chara)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['GabiteTalk']))
end

function base_camp_2_pmdras.Talking_Glimmora_Action(chara, activator)
    GROUND:CharTurnToChar(chara,CH('PLAYER'))
    UI:SetSpeaker(chara)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['GlimmoraTalk']))
end

function base_camp_2_pmdras.Talking_Carbink_Action(chara, activator)
    GROUND:CharTurnToChar(chara,CH('PLAYER'))
    UI:SetSpeaker(chara)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CarbinkTalk']))
end
--[[
function base_camp_2_pmdras.TopExit_Touch(obj, activator)
    DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  
    local dungeon_entrances = { }
    local ground_entrances = {{Flag=true,Zone='pmdras_overworld',ID=1,Entry=0}}
    COMMON.ShowDestinationMenu(dungeon_entrances,ground_entrances)
end

function base_camp_2_pmdras.BottomExit_Touch(obj, activator)
    DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    local dungeon_entrances = { 'undergrowths', 'cobblestone_cave', 'secret_gold_gulch', 'faded_trail', 'bramble_woods', 'trickster_woods', 'overgrown_wilds', 'moonlit_courtyard', 'ambush_forest', 'energy_garden', 'sickly_hollow', 'secret_garden'}
    local ground_entrances = {{Flag=true,Zone='pmdras_overworld',ID=2,Entry=0}},
    {Flag=SV.canyon_camp.ExpositionComplete,Zone='guildmaster_island',ID=5,Entry=0},
    {Flag=SV.rest_stop.ExpositionComplete,Zone='guildmaster_island',ID=6,Entry=0},
    {Flag=SV.final_stop.ExpositionComplete,Zone='guildmaster_island',ID=7,Entry=0},
    {Flag=SV.guildmaster_summit.GameComplete,Zone='guildmaster_island',ID=8,Entry=0}}
    COMMON.ShowDestinationMenu(dungeon_entrances,ground_entrances)
end
]]

-------------------------------
-- Entities Callbacks
-------------------------------


return base_camp_2_pmdras

