--[[
    init.lua
    Created: 07/11/2024 19:04:25
    Description: Autogenerated script file for the map groundwater_grotto.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local groundwater_grotto = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---groundwater_grotto.Init(zone)
--Engine callback function
function groundwater_grotto.Init(zone)


end

---groundwater_grotto.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function groundwater_grotto.EnterSegment(zone, rescuing, segmentID, mapID)


end

---groundwater_grotto.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function groundwater_grotto.ExitSegment(zone, result, rescue, segmentID, mapID)
    --DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    --PrintInfo("=>> ExitSegment_secret_gold_gulch result "..tostring(result).." segment "..tostring(segmentID))
  
    --first check for rescue flag; if we're in rescue mode then take a different path
    local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)
    if exited == true then
        --do nothing
    elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
        COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
    else
        if segmentID == 0 then
            COMMON.EndDungeonDay(result, 'pmdras_overworld', -1, 1, 0)
            COMMON.UnlockWithFanfare('undergrowths', true)
        else
            PrintInfo("No exit procedure found!")
            COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
        end
    end
end

---groundwater_grotto.Rescued(zone, name, mail)
--Engine callback function
function groundwater_grotto.Rescued(zone, name, mail)


end

return groundwater_grotto

