--[[
    init.lua
    Created: 03/21/2024 23:55:07
    Description: Autogenerated script file for the map cobblestone_cave_boss.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local cobblestone_cave_boss = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---cobblestone_cave_boss.Init(map)
--Engine callback function
function cobblestone_cave_boss.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---cobblestone_cave_boss.Enter(map)
--Engine callback function
function cobblestone_cave_boss.Enter(map)

    -- find the actors by name
    local boss = CH('Boss')
    local player = CH('PLAYER')
  
    -- set the game to cutscene mode to prevent idle anim
    GAME:CutsceneMode(true)
  
    -- show the title of the ground map, take 20 frames to do it.
    UI:WaitShowTitle(GAME:GetCurrentGround().Name:ToLocal(), 20);
    GAME:WaitFrames(30);
    -- fade out title, take 20 frames to do it.
    UI:WaitHideTitle(20);
  
    -- move the camera to a center at X248, Y216.  Do it in 1 frame.  Do not focus on player.
    GAME:MoveCamera(198, 108, 1, false)
  
    -- fade in, take 20 frames to do it.
    GAME:FadeIn(20)
  
    -- move the player up to position X240, Y248.  Do not use running animation.  Speed of 2.
    GROUND:MoveToPosition(player, 268, 296, false, 2)
  
    -- dialga talks.
    UI:SetSpeaker(boss)
    UI:WaitShowDialogue("I am the evil midnight bomber what bombs at midnight")

    COMMON.BossTransition(true)

    GAME:CutsceneMode(false)
  
    -- wait a little
    GAME:WaitFrames(20)
  
    -- go back to base camp
    GAME:EnterZone("cobblestone_cave", 0, 7, 0)

end

---cobblestone_cave_boss.Exit(map)
--Engine callback function
function cobblestone_cave_boss.Exit(map)


end

---cobblestone_cave_boss.Update(map)
--Engine callback function
function cobblestone_cave_boss.Update(map)


end

---cobblestone_cave_boss.GameSave(map)
--Engine callback function
function cobblestone_cave_boss.GameSave(map)


end

---cobblestone_cave_boss.GameLoad(map)
--Engine callback function
function cobblestone_cave_boss.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return cobblestone_cave_boss

