--[[
    init.lua
    Created: 07/20/2024 17:55:19
    Description: Autogenerated script file for the map yendor_knights_square.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local yendor_knights_square = {}

-------------------------------
-- Map Callbacks
-------------------------------
---yendor_knights_square.Init(map)
--Engine callback function
function yendor_knights_square.Init(map)


end

---yendor_knights_square.Enter(map)
--Engine callback function
function yendor_knights_square.Enter(map)

  GAME:FadeIn(20)

end

---yendor_knights_square.Exit(map)
--Engine callback function
function yendor_knights_square.Exit(map)


end

---yendor_knights_square.Update(map)
--Engine callback function
function yendor_knights_square.Update(map)


end

---yendor_knights_square.GameSave(map)
--Engine callback function
function yendor_knights_square.GameSave(map)


end

---yendor_knights_square.GameLoad(map)
--Engine callback function
function yendor_knights_square.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return yendor_knights_square

