--[[
    init.lua
    Created: 03/22/2024 19:27:59
    Description: Autogenerated script file for the map spore_caves.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local spore_caves = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---spore_caves.Init(zone)
--Engine callback function
function spore_caves.Init(zone)


end

---spore_caves.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function spore_caves.EnterSegment(zone, rescuing, segmentID, mapID)


end

---spore_caves.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function spore_caves.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---spore_caves.Rescued(zone, name, mail)
--Engine callback function
function spore_caves.Rescued(zone, name, mail)


end

return spore_caves

