--[[
    init.lua
    Created: 07/21/2024 17:29:10
    Description: Autogenerated script file for the map roguetown_library.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local roguetown_library = {}

-------------------------------
-- Map Callbacks
-------------------------------
---roguetown_library.Init(map)
--Engine callback function
function roguetown_library.Init(map)


end

---roguetown_library.Enter(map)
--Engine callback function
function roguetown_library.Enter(map)

  GAME:FadeIn(20)

end

---roguetown_library.Exit(map)
--Engine callback function
function roguetown_library.Exit(map)


end

---roguetown_library.Update(map)
--Engine callback function
function roguetown_library.Update(map)


end

---roguetown_library.GameSave(map)
--Engine callback function
function roguetown_library.GameSave(map)


end

---roguetown_library.GameLoad(map)
--Engine callback function
function roguetown_library.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return roguetown_library

