--[[
    init.lua
    Created: 03/21/2024 23:46:41
    Description: Autogenerated script file for the map cobblestone_cave.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local cobblestone_cave = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---cobblestone_cave.Init(zone)
--Engine callback function
function cobblestone_cave.Init(zone)


end

---cobblestone_cave.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function cobblestone_cave.EnterSegment(zone, rescuing, segmentID, mapID)


end

---cobblestone_cave.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function cobblestone_cave.ExitSegment(zone, result, rescue, segmentID, mapID)
    --DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    --PrintInfo("=>> ExitSegment_secret_gold_gulch result "..tostring(result).." segment "..tostring(segmentID))
  
    --first check for rescue flag; if we're in rescue mode then take a different path
    local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)
    if exited == true then
        --do nothing
    elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
        COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
    else
        if segmentID == 0 then
            COMMON.EndDungeonDay(result, 'pmdras_overworld', -1, 1, 0)
            COMMON.UnlockWithFanfare('groundwater_hollow', true)
            COMMON.UnlockWithFanfare('spore_caves', true)
            COMMON.UnlockWithFanfare('lava_pit', true)
        else
            PrintInfo("No exit procedure found!")
            COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
        end
    end
end

---cobblestone_cave.Rescued(zone, name, mail)
--Engine callback function
function cobblestone_cave.Rescued(zone, name, mail)


end

return cobblestone_cave

