--[[
    init.lua
    Created: 07/14/2024 17:25:14
    Description: Autogenerated script file for the map roguetown_explorer_base.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local roguetown_explorer_base = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---roguetown_explorer_base.Init(map)
--Engine callback function
function roguetown_explorer_base.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---roguetown_explorer_base.Enter(map)
--Engine callback function
function roguetown_explorer_base.Enter(map)

  GAME:FadeIn(20)

end

---roguetown_explorer_base.Exit(map)
--Engine callback function
function roguetown_explorer_base.Exit(map)


end

---roguetown_explorer_base.Update(map)
--Engine callback function
function roguetown_explorer_base.Update(map)


end

---roguetown_explorer_base.GameSave(map)
--Engine callback function
function roguetown_explorer_base.GameSave(map)


end

---roguetown_explorer_base.GameLoad(map)
--Engine callback function
function roguetown_explorer_base.GameLoad(map)

  GAME:FadeIn(20)

end

function roguetown_explorer_base.Talking_Sign_Action(chara, activator)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['SignTalk']))
end

function roguetown_explorer_base.Dungeon_Entrance_Touch(obj, activator)
    DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    local dungeon_entrances = { 'undergrowths', 'cobblestone_cave', 'groundwater_grotto', 'fire_pit', 'spore_caves', 'sandy_tombs'}
    local ground_entrances = {{Flag=true,Zone='pmdras_overworld',ID=2,Entry=1},
    {Flag=SV.canyon_camp.ExpositionComplete,Zone='guildmaster_island',ID=5,Entry=0},
    {Flag=SV.rest_stop.ExpositionComplete,Zone='guildmaster_island',ID=6,Entry=0},
    {Flag=SV.final_stop.ExpositionComplete,Zone='guildmaster_island',ID=7,Entry=0},
    {Flag=SV.guildmaster_summit.GameComplete,Zone='guildmaster_island',ID=8,Entry=0}}
    COMMON.ShowDestinationMenu(dungeon_entrances,ground_entrances)
end

-------------------------------
-- Entities Callbacks
-------------------------------


return roguetown_explorer_base

