--[[
    init.lua
    Created: 07/12/2024 11:43:44
    Description: Autogenerated script file for the map fire_pit.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local fire_pit = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---fire_pit.Init(zone)
--Engine callback function
function fire_pit.Init(zone)


end

---fire_pit.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function fire_pit.EnterSegment(zone, rescuing, segmentID, mapID)


end

---fire_pit.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function fire_pit.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---fire_pit.Rescued(zone, name, mail)
--Engine callback function
function fire_pit.Rescued(zone, name, mail)


end

return fire_pit

