--[[
    init.lua
    Created: 07/14/2024 11:43:16
    Description: Autogenerated script file for the map base_camp_1.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local base_camp_1 = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---base_camp_1.Init(map)
--Engine callback function
function base_camp_1.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---base_camp_1.Enter(map)
--Engine callback function
function base_camp_1.Enter(map)

  GAME:FadeIn(20)

end

---base_camp_1.Exit(map)
--Engine callback function
function base_camp_1.Exit(map)


end

---base_camp_1.Update(map)
--Engine callback function
function base_camp_1.Update(map)


end

---base_camp_1.GameSave(map)
--Engine callback function
function base_camp_1.GameSave(map)


end

---base_camp_1.GameLoad(map)
--Engine callback function
function base_camp_1.GameLoad(map)

  GAME:FadeIn(20)

end
-------------------------------
-- Entities Callbacks
-------------------------------

function base_camp_1.Talking_Dunsparce_Action(chara, activator)
    GROUND:CharTurnToChar(chara,CH('PLAYER'))
    UI:SetSpeaker(chara)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['DunsparceTalk']))
end

function base_camp_1.Talking_Graveler_Action(chara, activator)
    GROUND:CharTurnToChar(chara,CH('PLAYER'))
    UI:SetSpeaker(chara)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['GravelerTalk']))
end

function base_camp_1.TopExit_Touch(obj, activator)
    DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    local dungeon_entrances = { }
    local ground_entrances = {{Flag=true,Zone='pmdras_overworld',ID=1,Entry=0}}
    COMMON.ShowDestinationMenu(dungeon_entrances,ground_entrances)
end

function base_camp_1.BottomExit_Touch(obj, activator)
    DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    local dungeon_entrances = { 'undergrowths', 'cobblestone_cave', 'groundwater_grotto', 'fire_pit', 'spore_caves', 'sandy_tombs'}
    local ground_entrances = {{Flag=true,Zone='pmdras_overworld',ID=1,Entry=0},
    {Flag=SV.canyon_camp.ExpositionComplete,Zone='guildmaster_island',ID=5,Entry=0},
    {Flag=SV.rest_stop.ExpositionComplete,Zone='guildmaster_island',ID=6,Entry=0},
    {Flag=SV.final_stop.ExpositionComplete,Zone='guildmaster_island',ID=7,Entry=0},
    {Flag=SV.guildmaster_summit.GameComplete,Zone='guildmaster_island',ID=8,Entry=0}}
    COMMON.ShowDestinationMenu(dungeon_entrances,ground_entrances)
end


return base_camp_1

