--[[
    init.lua
    Created: 03/22/2024 11:35:44
    Description: Autogenerated script file for the map secret_gold_gulch.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local secret_gold_gulch = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---secret_gold_gulch.Init(zone)
--Engine callback function
function secret_gold_gulch.Init(zone)
    DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    PrintInfo("=>> Init_secret_gold_gulch")
end

---secret_gold_gulch.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function secret_gold_gulch.EnterSegment(zone, rescuing, segmentID, mapID)


end

---secret_gold_gulch.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function secret_gold_gulch.ExitSegment(zone, result, rescue, segmentID, mapID)
    DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    --PrintInfo("=>> ExitSegment_secret_gold_gulch result "..tostring(result).." segment "..tostring(segmentID))
  
    --first check for rescue flag; if we're in rescue mode then take a different path
    local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)
    if exited == true then
        --do nothing
    elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
        COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
    else
        if segmentID == 0 then
            COMMON.EndDungeonDay(result, 'pmdras_overworld', -1, 2, 0)
            COMMON.UnlockWithFanfare('secret_gold_gulch', true)
        else
            PrintInfo("No exit procedure found!")
            COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
        end
    end
end

---secret_gold_gulch.Rescued(zone, name, mail)
--Engine callback function
function secret_gold_gulch.Rescued(zone, name, mail)


end

return secret_gold_gulch

